# fly.toml app configuration file generated for 01projectmanager on 2023-05-12T17:18:30-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "01projectmanager"
primary_region = "bog"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
