# Generated by Django 4.1.7 on 2023-04-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
